name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *' # runs every hour

jobs:
  update-readme:
    name: Update my README stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
